# Generated by Django 3.1.4 on 2021-01-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.PositiveSmallIntegerField(choices=[(5, 'Request Information'), (4, 'Training in INTRA'), (3, 'Certification'), (2, 'Expertise / Consulting / Coaching'), (1, 'Training Funding'), (0, 'Others')], help_text='Be precise in your request and choose your subject.', verbose_name='subject')),
                ('gender', models.PositiveSmallIntegerField(choices=[(2, 'MR'), (1, 'MRS')], help_text='Gender.', verbose_name='gender')),
                ('first_name', models.CharField(help_text='First Name.', max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(help_text='Last Name.', max_length=255, verbose_name='last name')),
                ('organization', models.CharField(blank=True, help_text='Company / organization.', max_length=255, null=True, verbose_name='organization')),
                ('job_title', models.CharField(blank=True, help_text='Job title : CEO, CTO, Software Engineer, Trainee ..', max_length=255, null=True, verbose_name='job title')),
                ('phone', models.CharField(help_text='Phone.', max_length=20, verbose_name='phone')),
                ('email', models.EmailField(help_text='This email already exists.', max_length=255, unique=True, verbose_name='email')),
                ('message', models.TextField(help_text='Your message.', verbose_name='message')),
                ('subscribe', models.BooleanField(default=False, help_text='Would you like to receive our newsletter?', verbose_name='subscribe')),
                ('cc_myself', models.BooleanField(default=False, help_text='Send me a copy of the form.', verbose_name='cc myself')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'ordering': ('-created_at',),
            },
        ),
    ]
